### ISSUE TITLE
Move pipeline.yml file to repository

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/slurm-buildkite#2]
https://buildkite.com/docs/pipelines/defining-steps#adding-steps-pipeline-dot-yml-file

**Comment by jakebolewski** [comment]
we might want use the script generation option (generate the yaml with a script)

that would cut down a lot on the boilerplate and we could re-use the definitions that already exist (slurm-tests.toml)

**Comment by simonbyrne** [comment]
we might be able to just move the boilerplate to a setup script, e.g. so a single job would just be
```
commands:
  - central-gpu-setup.sh
  - mpiexec julia --project experiments/...
agents:
  - ntasks: 4
  - gres: "gpu:4"
```
