### ISSUE TITLE
Downstream testing

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/slurm-buildkite#46]
It looks like we could do this by having special labels on PRs, and using a [trigger pipeline](https://buildkite.com/docs/pipelines/trigger-step) with [conditionals](https://buildkite.com/docs/pipelines/conditionals#conditionals-in-steps). e.g. in ClimaCore-CI, we could have something like:
```yaml
- trigger: ClimaAtmos-CI
  if: build.pull_request.labels includes "test-climaatmos"
  build:
    env:
      CLIMACORE_COMMIT: ${BUILDKITE_COMMIT}
```
then the ClimaAtmos-CI pipeline would need some mechanism to override the ClimaCore commit in all projects if `CLIMACORE_COMMIT` is set.
