### ISSUE TITLE
Standard instance types

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/slurm-buildkite#9]
One of the challenges in reducing precompilation time is that different jobs will load different modules, in particular different MPI implementations. This requires doing a `Pkg.build("MPI")`, which will invalidate the precompilation cache, requiring a full precompilation.

With https://github.com/JuliaParallel/MPI.jl/pull/420, the cache will now only invalidate if the MPI implementation has changed. However if the agent previously had been configured to use a different MPI implementation, that would still require a round of precompilation.

We could address this with #8, but a simpler approach might be to standardize around a small set of module combinations. I was thinking we could use a `config` agent tag that could take different values, e.g., if `config=gpu` we would just need a hook that would do:
```sh
module purge
module load julia/1.4.2 cuda/10.0 openmpi/4.0.3_cuda-10.0 hdf5/1.10.1 netcdf-c/4.6.1

export JULIA_CUDA_USE_BINARYBUILDER: false
export JULIA_MPI_BINARY: system
```
and then give each config a different agent names (e.g. `central-gpu-%n` vs `central-cpu-%n`). These could be shared by different pipelines, even across different repositories.

A step in the .yml file would just need to be:
```yml
steps:
  - name: "heldsuarez"
    command: 
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate(); Pkg.build("MPI";verbose=true)'; Pkg.precompile()'"
      - "mpiexec julia --color=yes --project experiments/AtmosGCM/heldsuarez.jl"
    env:
      CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: true
    agents:
      queue: central
      config: gpu
      slurm_ntasks: 1
      slurm_gres: "gpu:1"
```
